#!/bin/bash
clear
lineas="===================================="
red='\033[1;31m'
green='\033[1;32m'
yellow='\033[1;33m'
blue='\033[1;34m'
magenta='\033[1;35m'
cyan='\033[1;36m'
reset='\033[0m'

printf $red
echo $lineas
echo "╻ ╻┏━┓╻ ╻╺┳┓┏━┓╻ ╻┏┓╻╻  ┏━┓┏━┓╺┳┓"
echo "┗┳┛┃ ┃┃ ┃ ┃┃┃ ┃┃╻┃┃┗┫┃  ┃ ┃┣━┫ ┃┃"
echo " ╹ ┗━┛┗━┛╺┻┛┗━┛┗┻┛╹ ╹┗━╸┗━┛╹ ╹╺┻┛"
echo $lineas

while true; do
    printf $green
    read -p "Que descargaras :
     [1] Música 
     [2] Salir " arch
    printf $reset

    case $arch in
        [Cc]ancion|Canción|canción|1)
            printf $red
            read -p "Que quieres descargar:
            [1] Canción 
            [2] Playlist 
            [3] Volver al menú principal " arch
            case $arch in
                [Cc]ancion|Canción|canción|1)
                    echo $lineas
                    read -p "Pega la URL de la canción _>" Ind
                    if [ -z $Ind ];then
                        echo $lineas
                        echo "No ingresante una url _>"
                        exit
                    fi

                    # Update download_dir to the desired path
                    download_dir="/storage/emulated/0/Download/KANMP3"
                    mkdir -p "$download_dir"

                    sleep 0.5
                    echo "Iniciando descarga _>"
                    yt-dlp -o "$download_dir/%(title)s.%(ext)s" -f bestaudio --embed-thumbnail --extract-audio --audio-format mp3 --audio-quality 0 "$Ind"
                    sleep 0.5 
                    echo $lineas
                    echo "Descarga finalizada, los archivos se encuentran en: $download_dir"
                    ;;
                [Pp]laylist|2)
                    read -p "Pega la URL de la playlist _>" Play
                    if [ -z $Play ];then
                        echo "No ingresante una url _>"
                        exit
                    fi
                    echo $lineas
                    sleep 0.5
                    echo "Preparando descarga _>"
                    yt-dlp -o "$download_dir/%(playlist_index)s. %(title)s.%(ext)s" --ignore-errors --format bestaudio --extract-audio --audio-format mp3 --audio-quality 160K --yes-playlist "$Play"
                    echo $lineas
                    ;;
                [Vv]olver|[3]|*)
                    break
                    ;;
            esac

            printf $reset
            ;;
        [Ss]alir|[2]|*)
            echo $lineas
            echo "<_Adiós_>"
            echo $lineas
            exit
            ;;
    esac
done
